### ISSUE TITLE
Linter is not working

### ISSUE THREAD

**Issue by ialecse** [mozilla/assay#128]
According to [this issue](https://github.com/mozilla/assay/issues/35)  linter has been integrated in Assay and the [documentation](https://mozilla-hub.atlassian.net/wiki/spaces/FDPDT/pages/454787301/Assay+Addon+Reviewer ) states that Assay will highlight any line flaggged by addons-linter. 
When testing an add-on that has a line flagged by linter in code manager, nothing is highlighted in VSC and also no message appears in the Problems pane of VSC.

Steps to reproduce:
1. Open add-on https://reviewers.addons.mozilla.org/en-US/reviewers/review/2870078 in VSC via Assay.  
2. Go to popup/popup.js line 25

Line 25 should be highlighted for _Unsafe assignment to innerHTML_, visible in code manager, but not in Assay

**Comment by chrstinalin** [comment]
Do you receive an error that linting has failed? If there's no response at all, is your VS Code workspace open directly on the version folder?

**Comment by ialecse** [comment]
The add-on was opened via the "Open in VSC" hyperlink from the review page so it is opened direcly on the version folder. 
I didn't see any error regarding linter when opening the add-on.

![image](https://github.com/user-attachments/assets/29331293-3452-4f00-afdc-31e36515176d)

**Comment by wagnerand** [comment]
The issue here is that the first linter message does not have a `file` property. over which Assay trips in `LintController.formatNotice`, presumably line 206 when trying to read a file from an undefined string argument (`const buffer = await this.directoryController.readFile(fileUri);`).

The error message also hints at that:
```
rejected promise not handled within 1 second: TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received undefined
extensionHostProcess.js:162
stack trace: TypeError: The "path" argument must be of type string. Received undefined
	at Object.join (node:path:1169:7)
	at LintController.getUriFromVersionPath (/Users/awagner/mozilla/assay/dist/extension.js:30939:37)
	at LintController.formatNotice (/Users/awagner/mozilla/assay/dist/extension.js:30913:30)
	at populateDiagnostic (/Users/awagner/mozilla/assay/dist/extension.js:30844:47)
	at LintController.lintWorkspace (/Users/awagner/mozilla/assay/dist/extension.js:30855:15)
	at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
```

Linter output for reference:
```
[
  {
    tier: 1,
    type: "warning",
    id: [
      "validation",
      "messages",
      "_MV3_COMPATIBILITY",
    ],
    message: "Manifest V3 compatibility warning",
    description: [
      "Firefox is adding support for manifest version 3 (MV3) extensions in Firefox 109.0, however, older versions of Firefox are only compatible with manifest version 2 (MV2) extensions. We recommend uploading Manifest V3 extensions as self-hosted for now to not break compatibility for your users.",
      "For more information about the MV3 extension roll-out or self-hosting MV3 extensions, visit <a href=\"https://mzl.la/3hIwQXX\" rel=\"nofollow\">https://mzl.la/3hIwQXX</a>",
    ],
    compatibility_type: null,
    extra: true,
  },
  {
    message: "Unsafe assignment to innerHTML",
    description: [
      "Due to both security and performance concerns, this may not be set using dynamic values which have not been adequately sanitized. This can lead to security issues or fairly serious performance degradation.",
    ],
    column: 5,
    file: "popup/popup.js",
    line: 25,
    uid: "08828fc119c644cfad6f4b32267734aa",
    type: "warning",
    id: [
      "UNSAFE_VAR_ASSIGNMENT",
    ],
    tier: 1,
  },
]
```
